[workspace]
resolver = "2"
members = [
    "src/ui",
    "src/web",
    "src/desktop",
    "src/mobile",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
ui = { path = "src/ui" }

