[package]
name = "mobile"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true, features = ["mobile"] }

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]

