[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true, features = ["desktop-web"] }
image = {workspace = true }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
