[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true, features = ["desktop-web"] }
web-sys = {version = "0.3.82", features = ["Navigator", "Window"]}

[features]
default = ["web"]
web = ["dioxus/web"]

